name: Ex-2
on: push
jobs:
 editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

 markdown-cli:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm i -g cli-markdown #instalirane na markdown
        name: install marcdown cli
        
      - run: md **/*.md #kudeto i da ima po papkite tam da otide da skanira
        name: run marcdown cli
  
 Build:
    needs: [editorconfig]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 
        with: 
          name: my-artifact
          path: .
          include-hidden-files: true

 Lintng:
    needs: Build
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download a single artifact # Name of the step
        uses: actions/download-artifact@v4 # Action to use
        with: # Parameters for the action
          name: my-artifact # Name of the artifact to download. Optional. If unspecified, all artifacts for the run are downloaded.
          path: .     # Destination path. Supports basic tilde expansion.  # Optional. Default is $GITHUB_WORKSPACE
      - name: Run linting
        uses: super-linter/super-linter/slim@v7 
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          


 
